// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A customer review moderation AI agent.
 *
 * - moderateReview - A function that handles the review moderation process.
 * - ModerateReviewInput - The input type for the moderateReview function.
 * - ModerateReviewOutput - The return type for the moderateReview function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ModerateReviewInputSchema = z.object({
  reviewText: z
    .string()
    .describe('The text content of the customer review to be moderated.'),
});
export type ModerateReviewInput = z.infer<typeof ModerateReviewInputSchema>;

const ModerateReviewOutputSchema = z.object({
  isAppropriate: z
    .boolean()
    .describe(
      'Whether the review is appropriate and does not contain spam, inappropriate language, or violate content guidelines.'
    ),
  reason: z
    .string()
    .optional()
    .describe(
      'If the review is not appropriate, provides a reason for the moderation decision.'
    ),
});
export type ModerateReviewOutput = z.infer<typeof ModerateReviewOutputSchema>;

export async function moderateReview(input: ModerateReviewInput): Promise<ModerateReviewOutput> {
  return moderateReviewFlow(input);
}

const moderateReviewPrompt = ai.definePrompt({
  name: 'moderateReviewPrompt',
  input: {schema: ModerateReviewInputSchema},
  output: {schema: ModerateReviewOutputSchema},
  prompt: `You are an AI content moderator for a restaurant review website. Your task is to determine whether a given customer review is appropriate for posting.

  Review the following customer review:
  {{{reviewText}}}

  Determine if the review contains any of the following:
  - Spam or irrelevant content
  - Offensive language, hate speech, or personal attacks
  - Promotion of illegal activities
  - Violation of community guidelines

  Based on your assessment, set the "isAppropriate" field to true if the review is suitable for posting, and false otherwise. If the review is not appropriate, provide a brief reason in the "reason" field.
  `, // Ensure newlines are included for readability
});

const moderateReviewFlow = ai.defineFlow(
  {
    name: 'moderateReviewFlow',
    inputSchema: ModerateReviewInputSchema,
    outputSchema: ModerateReviewOutputSchema,
  },
  async input => {
    const {output} = await moderateReviewPrompt(input);
    return output!;
  }
);
